CHANGELOG.md
scalr/data_source_current_run.go

Add new attribute `environment_id`
Change `workspace` attribute to be a workspace's name

SCALRCORE-16348 Update scalr_current_run

---

CHANGELOG.md
go.mod
go.sum
scalr/data_source_workspace.go
scalr/resource_scalr_workspace.go

SCALRCORE-16374: Add support for vcs-repo.path 

---

CHANGELOG.md
scalr/data_source_current_run.go

SCALRCORE-16424 Provider > data.scalr_current_run should not fail with local operations backend 

---

CHANGELOG.md
go.mod
go.sum
scalr/client_mock.go
scalr/data_source_workspace.go
scalr/data_source_workspace_ids.go
scalr/data_source_workspace_ids_test.go
scalr/data_source_workspace_test.go
scalr/provider.go
scalr/provider_test.go
scalr/resource_scalr_organization.go
scalr/resource_scalr_organization_test.go
scalr/resource_scalr_variable.go
scalr/resource_scalr_variable_test.go
scalr/resource_scalr_workspace.go
scalr/resource_scalr_workspace_test.go
scalr/testing.go
scalr/workspace_helpers.go
scalr/workspace_helpers_test.go
website/docs/d/workspace.html.markdown
website/docs/d/workspace_ids.html.markdown
website/docs/r/variable.html.markdown
website/docs/r/workspace.html.markdown

SCALRCORE-16386 Provider > Free from TFE branded naming (BC Change)

---

CHANGELOG.md
scalr/provider.go
website/docs/index.html.markdown

SCALRCORE-15489 TF > Scalr provider configuration from ENV (BC Change)

---

CHANGELOG.md
scalr/provider.go
website/docs/index.html.markdown

Reverts Scalr/terraform-provider-scalr#12

Revert "SCALRCORE-15489 TF > Scalr provider configuration from ENV (BC Change)"

---

CHANGELOG.md
scalr/provider.go
website/docs/index.html.markdown

Reverts Scalr/terraform-provider-scalr#15

Revert "Revert "SCALRCORE-15489 TF > Scalr provider configuration from ENV (BC Change)""

---

.github/PULL_REQUEST_TEMPLATE.md
GNUmakefile
README.md

SCALRCORE-16880 Provider > Update readme and add more detailed dev instructions

---

.github/PULL_REQUEST_TEMPLATE.md
GNUmakefile

SCALRCORE-16880 Fix Makefile command and add docs to PR template

---

scalr/data_source_workspace.go

Fix data_scalr_workspace - vcs_provider_id set

---

README.md

Update documentation URL after website update

---

scalr/resource_scalr_workspace.go

SCALRCORE-17092 Fix reference to environment ID

---

website/docs/r/endpoint.html.markdown

SCALRCORE-17281 Fix endpoint documentation

---

website/docs/d/current_run.html.markdown
website/docs/d/endpoint.html.markdown
website/docs/d/webhook.html.markdown
website/docs/d/workspace.html.markdown
website/docs/d/workspace_ids.html.markdown
website/docs/r/endpoint.html.markdown
website/docs/r/variable.html.markdown
website/docs/r/webhook.html.markdown
website/docs/r/workspace.html.markdown

* [X ] I have updated resource/data source documentation in [website/docs](https://github.com/Scalr/terraform-provider-scalr/tree/develop/website/docs)

revised wording

---

website/docs/d/current_run.html.markdown
website/docs/d/endpoint.html.markdown
website/docs/d/webhook.html.markdown
website/docs/d/workspace.html.markdown
website/docs/d/workspace_ids.html.markdown
website/docs/r/endpoint.html.markdown
website/docs/r/variable.html.markdown
website/docs/r/webhook.html.markdown
website/docs/r/workspace.html.markdown

Make wording consistent in all pages

---

docs/data-sources/scalr_environment.md
docs/data-sources/scalr_webhook.md
docs/data-sources/scalr_workspace.md
docs/resources/scalr_environment.md

* [X ] I have updated resource/data source documentation in [website/docs](https://github.com/Scalr/terraform-provider-scalr/tree/develop/website/docs)

SCALRCORE-17510 Environment review changes

---

docs/data-sources/scalr_environment.md
docs/resources/scalr_environment.md

Correct titles SCALRCORE-17510

---

CHANGELOG.md

Add scalr_server required version for 1.0.0-rc9

---

scalr/resource_scalr_workspace_migrate.go
scalr/resource_scalr_workspace_migrate_test.go

SCALRCORE-18077 Provider > Workspace vcs_repo migration panics due to invalid expected state

---

.github/workflows/default.yml
.goreleaser.yml

SCALRCORE-17943 Provider > Move CI/CD pipeline to the public repo (add goreleaser)

---

scalr/resource_scalr_variable_migrate.go
scalr/resource_scalr_workspace_migrate.go

SCALRCORE-18224: Provider > Fix inconsistency in migration

---

.github/workflows/default.yml
GNUmakefile
README.md

Add coveralls

---

scalr/resource_scalr_variable_test.go
scalr/resource_scalr_workspace_test.go

Fix vars tests

---

scalr/resource_scalr_variable.go

Multiscope variables: acc, env, ws are not ForceNew

---

scalr/resource_scalr_endpoint.go

SCALRCORE-18531 > Provider > Refresh state after manually endpoint deleting

---

CHANGELOG.md
GNUmakefile
scalr/resource_scalr_endpoint.go
scalr/resource_scalr_variable.go
scalr/resource_scalr_variable_test.go

SCALRCORE-18529 > Provider > Multiscope variables: Leftovers

---

CHANGELOG.md

SCALRCORE-18531 > Update changelog

---

.github/workflows/default.yml
.github/workflows/upstream.yml
GNUmakefile

SCALRCORE-16285: Drone > Run Scalr Provider acceptance test on merge into fatmouse master

---

CHANGELOG.md
scalr/resource_scalr_variable.go

SCALRCORE-19198 > Fix BC with scalr_variable resource

---

CHANGELOG.md
docs/resources/scalr_variable.md
go.mod
go.sum
scalr/resource_scalr_variable.go
scalr/resource_scalr_variable_migrate.go
scalr/resource_scalr_variable_migrate_test.go
scalr/resource_scalr_variable_test.go

SCALRCORE-18895 add variables state migration from env category to shell

---

CHANGELOG.md
docs/data-sources/scalr_workspace.md
docs/resources/scalr_workspace.md
go.mod
go.sum
scalr/data_source_workspace.go
scalr/data_source_workspace_test.go
scalr/resource_scalr_workspace.go
scalr/resource_scalr_workspace_test.go

SCALRCORE-18253 Scalr provider for before/after hooks

---

scalr/data_source_current_run_test.go
scalr/data_source_endpoint_test.go
scalr/helpers.go

SCALRCORE-15825 > Add acceptance tests for data.scalr_current_run

---

CHANGELOG.md
scalr/data_source_current_run_test.go
scalr/data_source_endpoint_test.go
scalr/data_source_environment_test.go
scalr/data_source_webhook_test.go
scalr/data_source_workspace_ids_test.go
scalr/data_source_workspace_test.go
scalr/helpers.go
scalr/resource_scalr_endpoint_test.go
scalr/resource_scalr_environment_test.go
scalr/resource_scalr_variable.go
scalr/resource_scalr_variable_test.go
scalr/resource_scalr_webhook_test.go
scalr/resource_scalr_workspace_test.go

SCALRCORE-19686 > Provider > Fail to create sensitive variable

---

CHANGELOG.md

SCALRCORE-19814 Scalr Provider > update changelog

---

CHANGELOG.md
docs/resources/scalr_variable.md
go.mod
go.sum
scalr/client_mock.go
scalr/resource_scalr_variable.go
scalr/resource_scalr_variable_migrate.go
scalr/resource_scalr_variable_migrate_test.go
scalr/resource_scalr_variable_test.go
scalr/testing.go

SCALRCORE-19435 add description attribute to the variable resource.

---

docs/data-sources/scalr_workspace.md
docs/resources/scalr_workspace.md
go.mod
go.sum
scalr/data_source_workspace.go
scalr/resource_scalr_workspace.go

SCALRCORE-19848 IaCP Provider > Workspace > Create workspace from module version

---

CHANGELOG.md
scalr/helpers.go
scalr/resource_scalr_access_policy.go
scalr/resource_scalr_access_policy_test.go
scalr/resource_scalr_environment.go
scalr/resource_scalr_environment_test.go
scalr/resource_scalr_role.go
scalr/resource_scalr_role_test.go
scalr/resource_scalr_webhook.go
scalr/resource_scalr_webhook_test.go
scalr/resource_scalr_workspace.go

SCALRCORE-19995 > Provider >  Handle empty strings in policy_groups attribute

---

CHANGELOG.md
go.mod
go.sum
scalr/client_mock.go
scalr/data_source_current_run.go
scalr/data_source_endpoint.go
scalr/data_source_environment.go
scalr/data_source_scalr_access_policy.go
scalr/data_source_webhook.go
scalr/data_source_workspace.go
scalr/resource_scalr_access_policy.go
scalr/resource_scalr_endpoint.go
scalr/resource_scalr_environment.go
scalr/resource_scalr_role.go
scalr/resource_scalr_variable.go
scalr/resource_scalr_webhook.go
scalr/resource_scalr_workspace.go

SCALRCORE-18723 Fix Provider to handle 404 error

---

CHANGELOG.md
scalr/resource_scalr_environment.go

SCALRCORE-20057 Provider > Crash when account does not have correct permissions

---

CHANGELOG.md
scalr/data_source_environment.go
scalr/data_source_environment_test.go
scalr/data_source_scalr_access_policy.go
scalr/data_source_scalr_access_policy_test.go

SCALRCORE-19951 handle ResourceNotFound error for data sources correctly

---

CHANGELOG.md
scalr/resource_scalr_workspace.go

SCALRCORE-20034  Workspaces > Mark `configuration version root` attribute as deprecated

---

scalr/helpers.go

SCALRCORE-19663 Scalr Provider > Environment data source > Filtering by name

---

README.md

Readme > Fix scalr provider source

---

docs/data-sources/scalr_role.md

updated scalr_role.md

---

CHANGELOG.md
docs/data-sources/scalr_environment.md
docs/resources/scalr_run_triggers.md

updated CHANGELOG

---

docs/resources/scalr_run_triggers.md

fixed triggers docs

---

docs/resources/scalr_workspace.md

improve workspaces docs

---

CHANGELOG.md
docs/data-sources/scalr_workspace.md
docs/resources/scalr_workspace.md
go.mod
go.sum
scalr/resource_scalr_workspace.go
scalr/resource_scalr_workspace_test.go

SCALRCORE-21151 Workspaces > Enable option to extend backend time-out to self set number

---

.github/workflows/default.yml

rc28 > fix version of gcloud

---

CHANGELOG.md
scalr/resource_scalr_variable.go
scalr/resource_scalr_variable_test.go

SCALRCORE-20211 Provider > Confusing error for multi-scope variables

---

CHANGELOG.md
go.mod
go.sum

SCALRCORE-21546 Scalr Provider > remove environments include from PolicyGroup resource

---

.github/workflows/default.yml
scripts/upload.sh

SCALRCORE-21545 > Release terraform-provider-scalr into development registry

---

.github/workflows/default.yml

SCALRCORE-21545 > Fix provider version namings in registry

---

CHANGELOG.md
docs/resources/scalr_workspace_run_schedule.md

update CHANGELOG.md and scalr_workspace_run_schedule.md

---

.github/workflows/default.yml
scripts/upload.sh

SCALRCORE-22008 > Validate tag in release job

---

go.mod
go.sum

Closing CVE-2022-30323

---

CHANGELOG.md
docs/data-sources/scalr_workspace.md
docs/resources/scalr_workspace.md
go.mod
go.sum
scalr/data_source_workspace.go
scalr/data_source_workspace_test.go
scalr/resource_scalr_workspace.go
scalr/resource_scalr_workspace_test.go

SCALRCORE-22110 Provider - Workspace > pre-init, post-init custom hooks

---

docs/resources/scalr_provider_configuration.md
go.mod
go.sum
scalr/resource_scalr_provider_configuration.go
scalr/resource_scalr_provider_configuration_test.go

SCALRCORE-20644 Provider configurations > API > Google Provider

---

scalr/resource_scalr_variable.go
scalr/resource_scalr_variable_test.go

CALRCORE-22117 Plan failing when changing scalr_variable resource

---

CHANGELOG.md

fix/SCALRCORE 22117 Update changelog

---

docs/resources/scalr_workspace.md

SCALRCORE-22261 Workspace tags, fix docs

---

CHANGELOG.md

account_id

---

.github/workflows/default.yml
.github/workflows/upstream.yml
scalr/provider.go
scalr/resource_scalr_webhook.go

Pass workflow id into container metadata

---

CHANGELOG.md
scalr/data_source_scalr_policy_group.go

SCALRCORE-23094 Scalr Provider > Policy groups > Invalid value 'environments' for include

---

CHANGELOG.md
docs/data-sources/scalr_variable.md
docs/data-sources/scalr_variables.md

updated CHANGELOG.md

---

docs/data-sources/scalr_workspace.md
docs/resources/scalr_workspace.md
go.mod
go.sum
scalr/data_source_workspace.go
scalr/data_source_workspace_test.go
scalr/resource_scalr_workspace.go
scalr/resource_scalr_workspace_test.go

SCALRCORE-23652 - Workspaces > Auto-queue runs

---

scalr/data_source_workspace_test.go
scalr/resource_scalr_workspace_test.go

Update TF version

---

CHANGELOG.md

updated the CHANGELOG.md

---

.github/workflows/default.yml
.github/workflows/upstream.yml

SCALRCORE-24559: Move downstream provider tests to TEv2

---

.github/workflows/default.yml
.github/workflows/upstream.yml

SCALRCORE-22125: Add e2e prefix to TEv2 container names

---

.github/workflows/default.yml
.github/workflows/upstream.yml

SCALRCORE-22125: Update TEv2 container request options

---

.github/workflows/default.yml
.github/workflows/upstream.yml

SCALRCORE-247291: Don't pass fatmouse/scalr master branch during TEv2 request

---

CHANGELOG.md

fixed CHANGELOG.md

---

.github/workflows/default.yml
.github/workflows/upstream.yml

SCALRCORE-25060: TEv2 > Don't build UI for provider_upstream

---

scalr/resource_scalr_provider_configuration_default.go

SCALRCORE-25455 Scalr Provider > scalr_provider_configuration_default resource > Change the text of the errors

---

CHANGELOG.md
docs/data-sources/scalr_current_run.md
scalr/data_source_scalr_current_run.go
scalr/data_source_scalr_current_run_test.go
scalr/helpers.go

SCALRCORE-25684 Provider > bug in terraform provider of scalr 1.0.3

---

CHANGELOG.md
scalr/resource_scalr_account_allowed_ips.go
scalr/resource_scalr_account_allowed_ips_test.go

SCALRCORE-25525: scalr_account_allowed_ips: accept /32 suffix

---

docs/resources/scalr_environment.md
scalr/resource_scalr_environment.go

SCALRCORE-25768 [Provider] Provider Credentials > Forbid creation and hide for users who doesn't have it.

---

docs/data-sources/scalr_access_policy.md

reverted scalr_access_policy doc deletion

---

CHANGELOG.md
docs/data-sources/scalr_agent_pool.md
docs/data-sources/scalr_vcs_provider.md
docs/resources/scalr_agent_pool.md
docs/resources/scalr_vcs_provider.md
go.mod
go.sum
scalr/data_source_scalr_agent_pool.go
scalr/data_source_scalr_vcs_provider.go
scalr/resource_scalr_agent_pool.go
scalr/resource_scalr_vcs_provider.go
scalr/resource_scalr_workspace.go

Provider > Add link API between on-prem VCS and Agent-Pool

---

CHANGELOG.md
docs/data-sources/scalr_agent_pool.md
docs/data-sources/scalr_vcs_provider.md
docs/resources/scalr_agent_pool.md
docs/resources/scalr_vcs_provider.md
go.mod
go.sum
scalr/data_source_scalr_agent_pool.go
scalr/data_source_scalr_vcs_provider.go
scalr/resource_scalr_agent_pool.go
scalr/resource_scalr_vcs_provider.go
scalr/resource_scalr_workspace.go

Reverts Scalr/terraform-provider-scalr#233

Revert "Provider > Add link API between on-prem VCS and Agent-Pool"

---

CHANGELOG.md
docs/data-sources/scalr_endpoint.md
docs/data-sources/scalr_webhook.md
docs/resources/scalr_endpoint.md
docs/resources/scalr_webhook.md
go.mod
go.sum
scalr/data_source_scalr_endpoint.go
scalr/data_source_scalr_webhook.go
scalr/data_source_scalr_webhook_test.go
scalr/helpers.go
scalr/resource_scalr_endpoint.go
scalr/resource_scalr_webhook.go
scalr/resource_scalr_webhook_migrate.go
scalr/resource_scalr_webhook_test.go

SCALRCORE-24801 Integrations > Webhook update provider resource

---

CHANGELOG.md
docs/data-sources/scalr_agent_pool.md
docs/data-sources/scalr_vcs_provider.md
docs/resources/scalr_agent_pool.md
docs/resources/scalr_vcs_provider.md
go.mod
go.sum
scalr/data_source_scalr_agent_pool.go
scalr/data_source_scalr_vcs_provider.go
scalr/resource_scalr_agent_pool.go
scalr/resource_scalr_vcs_provider.go
scalr/resource_scalr_workspace.go

Reverts Scalr/terraform-provider-scalr#237

Revert "Revert "Provider > Add link API between on-prem VCS and Agent-Pool""

---

CHANGELOG.md
scalr/resource_scalr_provider_configuration.go
scalr/resource_scalr_provider_configuration_test.go

SCALRCORE-25049 Provider > Import scalr_provider_configuration

---

CONTRIBUTING.md

SCALRCORE-25919 Terraform provider > add documentation with best practices for provider development

---

CHANGELOG.md
go.mod
go.sum
scalr/resource_scalr_provider_configuration_default.go

SCALRCORE-25911 Provider > scalr_policy_group_linkage > Provider produced inconsistent result after apply

---

.github/workflows/default.yml
.github/workflows/upstream.yml

SCALRCORE-26514 API > delete codebase that related to global access

---

.github/workflows/default.yml
.github/workflows/upstream.yml

SCALRCORE-27284: Support resources_preset tev2 var for managing container resources

---

.github/workflows/default.yml
.github/workflows/upstream.yml
README.md

SCALRCORE-26666: Move all branch and image detection logic from shell to cli te up command

---

CHANGELOG.md
docs/resources/scalr_provider_configuration.md
go.mod
go.sum
scalr/resource_scalr_provider_configuration.go
scalr/resource_scalr_provider_configuration_test.go

SCALRCORE-26905 Provider configurations > Google > Workload identity

---

go.mod

SCALRCORE-25795 - Scalr provider > Invalid error of failed runs

---

CHANGELOG.md
docs/resources/scalr_provider_configuration.md

SCALRCORE-27601 fix aws provider configuration docs.

---

CHANGELOG.md
docs/resources/scalr_provider_configuration.md
go.mod
go.sum
scalr/resource_scalr_provider_configuration.go

SCALRCORE-27395 Azure OIDC support.

---

.github/workflows/default.yml
.github/workflows/upstream.yml

SCALRCORE-28027 Updating e2e action to create test app on the agent pool

---

CHANGELOG.md
docs/resources/vcs_provider.md
go.mod
go.sum
scalr/resource_scalr_vcs_provider.go
scalr/resource_scalr_vcs_provider_test.go

SCALRCORE-28034 [tf-provider] Provider > Ignore draft PR

---

CHANGELOG.md

Bump changelog to v1.5.0

---

CHANGELOG.md
docs/data-sources/vcs_provider.md
scalr/data_source_scalr_vcs_provider.go
scalr/data_source_scalr_vcs_provider_test.go

SCALRCORE-28700 Provider > Add Ignore draft PR to Data Source scalr_vcs_provider

---

CHANGELOG.md
scalr/resource_scalr_variable.go
scalr/resource_scalr_variable_test.go

SCALRCORE-21026 Multi-scope Terraform variables

---

CHANGELOG.md

Bump changelog to v1.7.0

---

CHANGELOG.md
docs/resources/policy_group.md
docs/resources/policy_group_linkage.md
scalr/resource_scalr_policy_group.go
scalr/resource_scalr_policy_group_linkage.go

SCALRCORE-29726 BE > Provider > Policy linkage > Environment unlinks from policy group after re-run

---

CHANGELOG.md

Bump changelog to v1.8.0

---

CHANGELOG.md

Bump changelog for v1.9.0

---

.github/workflows/release.yml

Do not approve docs publish

---

CHANGELOG.md
CONTRIBUTING.md

SCALRCORE-29053 Add documentation for Scalr Provider changelog

---

.github/workflows/default.yml
.github/workflows/docs.yml
.github/workflows/release.yml
.github/workflows/upstream.yml

SCALRCORE-30278: GH Actions: Update deprecated actions

---

.github/workflows/default.yml
CHANGELOG.md
scalr/resource_scalr_iam_team.go

SCALRCORE-30200 Provider > Create team > Optional attribute affect real infrastructure but shouldn't

---

.github/workflows/default.yml

SCALRCORE-30933: CI > Provider > Broken development builds versioning

---

.github/workflows/default.yml
CHANGELOG.md
docs/data-sources/provider_configuration.md
docs/resources/provider_configuration.md
go.mod
go.sum
scalr/data_source_scalr_provider_configuration.go
scalr/data_source_scalr_provider_configuration_test.go
scalr/resource_scalr_provider_configuration.go
scalr/resource_scalr_provider_configuration_test.go

SCALRCORE-30896 Provider configurations owners

---

CHANGELOG.md

Bump changelog for v1.10.0

---

CHANGELOG.md
go.mod
go.sum

SCALRCORE-31036: Update api-client version

---

CHANGELOG.md

Update changelog for v1.11.0

---

.github/workflows/default.yml
.github/workflows/release.yml
.goreleaser.yml

SCALRCORE-31551 Provider > Adopt BC changes in GoReleaser v2

---

CHANGELOG.md

SCALRCORE-31246: Bump required release

---

CHANGELOG.md

Update changelog for v1.12.0

---

.github/actions/update-network-mirror/dist/index.js
.github/actions/update-network-mirror/index.js
.github/workflows/default.yml
.github/workflows/release.yml

do not merge pls

---

.github/workflows/default.yml
.github/workflows/upstream.yml

SCALRCORE-31781 > SRE: Service Accounts Housekeeping for Repositories

---

.github/workflows/default.yml

fixed release upload to staging registry

---

CHANGELOG.md

Update CHANGELOG.md v2.0.0

---

CHANGELOG.md
docs/resources/workspace.md
go.mod
go.sum
scalr/data_source_scalr_workspace.go
scalr/data_source_scalr_workspace_test.go
scalr/resource_scalr_workspace.go
scalr/resource_scalr_workspace_test.go

SCALRCORE-31852 Add environment type in the Scalr provider.

---

CHANGELOG.md
scalr/resource_scalr_variable.go
scalr/resource_scalr_variable_test.go

SCALRCORE-32209 Provider > Variables: force new when changing some attributes of a sensitive variable

---

.github/workflows/default.yml

fixed release build

---

.goreleaser.yml
CHANGELOG.md
docs/resources/webhook.md
scalr/resource_scalr_environment.go
scalr/resource_scalr_provider_configuration.go
scalr/resource_scalr_provider_configuration_test.go
scalr/resource_scalr_service_account.go
scalr/resource_scalr_service_account_test.go
scalr/resource_scalr_webhook.go
scalr/resource_scalr_workspace.go

SCALRCORE-31421 [Scalr Provider] > Resource is drifted even there are no changes

---

CHANGELOG.md
scalr/data_source_scalr_variables_test.go
scalr/resource_scalr_variable.go

SCALRCORE-31259 Variables > force hcl flag for shell category variables

---

.gitignore
CHANGELOG.md
docs/data-sources/variable.md
docs/resources/variable.md
go.mod
go.sum
scalr/data_source_scalr_variable.go
scalr/data_source_scalr_variable_test.go
scalr/data_source_scalr_variables.go
scalr/data_source_scalr_variables_test.go
scalr/resource_scalr_variable.go
scalr/resource_scalr_variable_test.go

SCALRCORE-32442 Show who and when created/updated the variable

---

.github/workflows/default.yml
.github/workflows/docs.yml
.github/workflows/release.yml

Bump Readme version to v0.0.5

---

scalr/data_source_scalr_webhook_test.go

SCALRCORE-30859 make `secret-key` webhook attribute sensitive

---

docs/data-sources/ssh_key.md
docs/data-sources/tag.md
docs/data-sources/variable.md
docs/data-sources/variables.md
docs/data-sources/vcs_provider.md
docs/data-sources/webhook.md
docs/data-sources/workspace.md
docs/data-sources/workspace_ids.md
docs/data-sources/workspaces.md
scalr/data_source_scalr_webhook_test.go

Fixed the test that checks webhook secret_key

---

.github/workflows/backport.yaml

SCALRCORE-33055 > Implement 2-pr backport method

---

CHANGELOG.md

Update CHANGELOG.md v2.2.0

---

.github/workflows/backport.yaml

changed backport runner

---

CHANGELOG.md

Update CHANGELOG.md v2.3.0

---

CHANGELOG.md
docs/resources/workspace.md
go.mod
go.sum
internal/provider/helpers.go
internal/provider/resource_scalr_workspace.go
internal/provider/resource_scalr_workspace_test.go

SCALRCORE-33497 Provider > Manage remote state consumers

---

CHANGELOG.md

Update CHANGELOG.md v2.4.0

---

go.mod
go.sum

SCALRCORE-33786 Bump yamux to 0.1.2 version

---

internal/provider/workspace_resource.go
internal/provider/workspace_schemas.go

Remove default value for scalr_workspace.auto_queue_runs attribute

---

docs/index.md
examples/provider/usage.tf

Update provider version in usage example

---

CHANGELOG.md

Update CHANGELOG.md v2.6.0

---

CHANGELOG.md

Update CHANGELOG.md v3.0.0

---

.github/workflows/dependabot-to-jira.yml

SCALRCORE-33092: Automation > Automate Jira creation process for Dependabot issues

---

CHANGELOG.md

Update CHANGELOG.md v3.1.0

---

CHANGELOG.md

Fix changelog for 3.1.0

---

CHANGELOG.md

Update changelog for v3.2.0

---

CHANGELOG.md
docs/resources/provider_configuration.md
examples/resources/scalr_provider_configuration/aws-default-tags.tf
go.mod
go.sum
internal/provider/resource_scalr_provider_configuration.go
internal/provider/resource_scalr_provider_configuration_test.go
templates/resources/provider_configuration.md.tmpl

SCALRCORE-28930 Scalr Provider > Provider configurations > AWS: Default tags

---

CHANGELOG.md
GNUmakefile
docs/data-sources/environment.md
docs/resources/environment.md
go.mod
go.sum
internal/provider/environment_data_source.go
internal/provider/environment_resource.go

SCALRCORE-35004 Default agent pool in the environment

---

CHANGELOG.md

Update CHANGELOG.md v3.5.0

---

CHANGELOG.md
internal/provider/resource_scalr_agent_pool.go

SCALRCORE-35613 - Provider > Failed to determine default value for deprecated arguments from local environment

---

CHANGELOG.md
docs/data-sources/assume_service_account_policy.md
docs/resources/assume_service_account_policy.md
internal/provider/assume_service_account_policy_data_source.go
internal/provider/assume_service_account_policy_resource.go
internal/provider/assume_service_account_policy_resource_test.go

SCALRCORE-35813: renamed assume operator "like" into "contains"

---

CHANGELOG.md

Bump version to 3.8.0 and update changelog

---

.github/workflows/security-jira-ticket.yml

SCALRCORE-35987: SRE: Code Scanning Jira Tickets
